Mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls'))
]

mysite/urls.py
from django.urls import path, re_path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'mysite'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^about/', views.about, name='about'),
    re_path(r'^services/', views.services, name='services'),
    re_path(r'^practivities/', views.practivities, name='practivities'),
    re_path(r'^news/', views.news, name='news'),
    re_path(r'^contact/', views.contact, name='contact')
]

mysite/models.py
from django.db import models


from django.core import validators
from django.core.exceptions import ValidationError

from django import forms
import os
import datetime


class Contact(models.Model):
    firstname = models.CharField(max_length=200)
    lastname = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    message = models.CharField(max_length=200)

    def __str__(self):
        return self.name

mysite/forms.py
from django import forms
from . import models


class ContactForm(forms.ModelForm):
    firstname = forms.CharField(max_length=264, widget=forms.TextInput(
        attrs={'placeholder': 'First Name', 'class': 'form-control', 'id': 'fname'}))

    lastname = forms.CharField(max_length=264, widget=forms.TextInput(
        attrs={'placeholder': 'Last Name', 'class': 'form-control', 'id': 'lname'}))

    email = forms.CharField(max_length=264, widget=forms.TextInput(
        attrs={'placeholder': 'Email', 'class': 'form-control', 'id': 'email'}))

    phone = forms.CharField(max_length=264, widget=forms.TextInput(
        attrs={'placeholder': 'Phone', 'class': 'form-control', 'id': 'phone'}))

    message = forms.CharField(max_length=264, widget=forms.Textarea(
        attrs={"rows": 5, "cols": 20, 'placeholder': 'Write your message', 'class': 'form-control',
               'id': 'message'}))

    class Meta:
        fields = ('firstname', 'lastname', 'email', 'phone', 'message')
        model = models.Contact

mysite/views.py
from django.contrib.messages.api import success
from django.http.response import HttpResponse
from .models import Contact
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

from collections import namedtuple
from django.contrib import messages
from django.shortcuts import redirect, render
from django.views.generic import ListView, CreateView, DeleteView, DetailView
from . import models
from . import forms
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponseRedirect


def index(request):
    return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')


def services(request):
    return render(request, 'services.html')


def news(request):
    return render(request, 'news.html')


def practivities(request):
    return render(request, 'practivities.html')


def contact(request):
    contact = models.Contact.objects.all()
    form = forms.ContactForm()

    if request.method == 'POST':
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        email = request.POST['email']
        phone = request.POST['phone']
        message = request.POST['message']

        New = Contact(
            firstname=firstname,
            lastname=lastname,
            email=email,
            phone=phone,
            message=message)

        data = {
            'firstname': firstname,
            'lastname': lastname,
            'email': email,
            'phone': phone,
            'message': message
        }

        message = '''
        The message is sent by: {} {}

        Email_id: {}
        Phone No: {}
        Message: {}

        '''.format(data['firstname'], data['lastname'], data['email'], data['phone'], data['message'])
        send_mail(data['email'], message, '', ['bbchanna@gmail.com'])

        form = forms.ContactForm(request.POST)
        if form.is_valid():
            form.save()
            form = forms.ContactForm()
            messages.success(
                request, 'Thanks for your Message.We will reach back to you soon.')
            success = 'Thanks for your Message.We will reach back to you soon.'
            return HttpResponse(success)
            # return render(request, 'contact.html', {'form': form})

    context = {'form': form}
    return render(request, 'contact.html', context)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block index %}

<head>
    <link rel="stylesheet" href="{% static 'mysite/about/about.css' %}">
</head>
<header>   
<section class="about">
    <div class="aboutbg">
        <h1>About Us</h1>

    </div>
    <div data-aos="fade" class="title">
        
        <p>Press PR is Kashmir based public relation company founded by a young group of local journalists. Our team has
            a vast
            work experience in the media sector like print, broadcast and advertising which helps our clients achieve
            business
            targets through effective and targeted communication.
            We design our strategies as per the needs and demands of our clients so as to give them maximum leverage of
            brand image
            in the market through our dedicated staff.
            Our approach to PR and marketing communications means your messages will resonate, win you recognition and
            deliver a
            return on investment.
            As Kashmir is an untapped market, the companies can hire our service to leverage their brand in this region.
        </p>
    </div>

</section>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <link rel="icon" type="image/x-icon" href="{% static 'mysite/assets/favicon.ico' %}">
    <!-- CDN Link for animation on Scroll -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <!-- R -->
    <link rel="stylesheet" href="{% static 'mysite/testimonials/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- All CSS links should be linked here -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/v4-shims.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
    <!-- for Our Clients -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- All CSS files should be linked here -->

    <link rel="stylesheet" href="{% static 'mysite/base/base.css' %}">
    <link rel="stylesheet" href="{% static 'mysite/index/index.css' %}">

</head>

<body>
    <nav class="navbar1">
        <div class="barleft">
            <div class="menubtn ">
                <!-- <div class="menubtn__burger"></div> -->
                <button class="menubtn" onclick="this.classList.toggle('opened');this.setAttribute('aria-expanded', this.classList.contains('opened'))" aria-label="Main Menu">
                    <svg width="100" height="50" viewBox="0 0 10 110">
                      <path class="line line1" d="M 20,29.000046 H 80.000231 C 80.000231,29.000046 94.498839,28.817352 94.532987,66.711331 94.543142,77.980673 90.966081,81.670246 85.259173,81.668997 79.552261,81.667751 75.000211,74.999942 75.000211,74.999942 L 25.000021,25.000058" />
                      <path class="line line2" d="M 20,50 H 80" />
                      <path class="line line3" d="M 20,70.999954 H 80.000231 C 80.000231,70.999954 94.498839,71.182648 94.532987,33.288669 94.543142,22.019327 90.966081,18.329754 85.259173,18.331003 79.552261,18.332249 75.000211,25.000058 75.000211,25.000058 L 25.000021,74.999942" />
                    </svg>
                  </button>
            </div>
        </div>

        <div class="logomobile"><a href="{% url 'mysite:index' %}"><img src="{% static 'mysite/assets/logo1.png' %}"
                    alt=""></a></div>

        <ul class="navbar ull">
            <div class="logo"><a href="{% url 'mysite:index' %}"><img src="{% static 'mysite/assets/logo1.png' %}"
                        alt=""></a></div>
            <li><a href="{% url 'mysite:index' %}" class="menu-btn">Home</a></li>
            <li><a href="{% url 'mysite:about' %}" class="menu-btn">About</a></li>
            <li><a href="{% url 'mysite:services' %}"class="menu-btn">Services</a></li>
            <li><a href="{% url 'mysite:news' %}" class="menu-btn">News</a></li>
            <li><a href="{% url 'mysite:practivities' %}" class="menu-btn">PR Activities</a></li>
            <div class="cnnt"><a href="{% url 'mysite:contact' %}" class="contactbtn1"><b>Contact</b></a></div>

        </ul>
    </nav>
    <!-- Add Home Page(index.html) here -->
    {% block index %}
    {% endblock %}
    <!-- testmonials -->
    <!-- {% block testimonials %}
    {% endblock %} -->
    <!-- Add About Page here -->
    <!-- Social Media Icons -->
    <div class="container1">
        <div class="box">
            <div class="icon instagram">
                <a href="https://www.instagram.com/presspr1/"> <i class="fab fa-instagram fa-2x"></i></a>
            </div>
            <p><a style="text-decoration: none;" href="https://www.instagram.com/presspr1/"> Instagram</a></p>
        </div>
        <div class="box">
            <div class="icon facebook">
                <a href="https://www.facebook.com/kashmir.pr/"><i class="fab fa-facebook fa-2x"></i></a>
            </div>
            <p><a style="text-decoration: none;" href="https://www.facebook.com/kashmir.pr/"> Facebook</a></p>
        </div>
        <div class="box">
            <div class="icon twitter">
                <a href="https://twitter.com/kralyarisajad"> <i class="fab fa-twitter fa-2x"></i></a>
            </div>
            <p><a style="text-decoration: none;" href="https://twitter.com/kralyarisajad"> Twitter</a></p>
        </div>
        <div class="box">
            <div class="icon whatsapp">
                <a href="https://wa.me/91941958775"><i class="fab fa-whatsapp fa-2x"></i></a>
            </div>
            <p><a style="text-decoration: none;" href="https://wa.me/919419584775"> Whatsapp</a></p>
        </div>
    </div>
    <!-- Back to Top Button -->
    <div class="scroll-up-btn">
        <a href="#"> <i class="blink_me fa fa-angle-double-up" aria-hidden="true"></i>
    </div>

    <!-- footer here for all -->
    <footer class="footer-distributed footer">

        <div class="footer-left">

            <img class="footerlogo" src="{% static 'mysite/assets/logo1.png' %}" alt="logo">

            <p class="footer-links">
                <a href="#" class="link-1">Home</a>

                <a href="{% url 'mysite:about' %}">About</a>

                <a href="{% url 'mysite:services' %}">Services</a>

                <a href="{% url 'mysite:news' %}">News</a>

                <a href="{% url 'mysite:practivities' %}">Pr Activities</a>

                <a href="{% url 'mysite:contact' %}">Contact</a>
            </p>

            <p class="footer-company-name"></p>
        </div>

        <div class="footer-center">

            <div>
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <p><span>Sairaa Building, Ist floor,Madina Chowk, Gawkadal, Lal Chowk</span>Srinagar, Jammu and Kashmir
                    190001, IN</p>
            </div>

            <div>
                <i class="fa fa-phone"></i>
                <p><a href="tel:+91-9419584775"> +91-9419584775</a></p>
            </div>

            <div>
                <i class="fa fa-envelope"></i>
                <p><a href="mailto:press.pr.kmr@gmail.com">press.pr.kmr@gmail.com</a></p>
            </div>

        </div>

        <div class="footer-right">

            <p class="footer-company-about">
                <span><b> About the company</b></span>
                Press PR is Kashmir based public relation company founded by a young group of local journalists. Our
                team
                has a vast work experience in the media sector like print, broadcast and advertising which helps our
                clients
                achieve business targets through effective and targeted communication.
            </p>

            <div class="footer-icons">

                <a href="https://www.facebook.com/kashmir.pr/"><i class="fa fa-facebook"></i></a>
                <a href="https://twitter.com/kralyarisajad"><i class="fa fa-twitter"></i></a>
                <a href="https://in.linkedin.com/company/press-pr"><i class="fa fa-linkedin"></i></a>
                <a href="https://www.instagram.com/presspr1/"><i class="fa fa-instagram"></i></a>

            </div>

        </div>
        

    </footer>
    <!-- footer section -->
<div class="ftr" style="background-color: black; padding: 20px 23px; color: #fff;">
    <span>Created By<a href="http://www.basitchanna.com"> Basit Bilal Channa | </a> <span class="fa fa-copyright"></span> Press Pr 2021 All rights reserved.</span>
</div>
</body>
<!-- All JavaScript links should be linked here -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- R -->
<script src="{% static 'mysite/testimonials/scripts.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.8/swiper-bundle.min.js"></script>
<!-- for OurClients -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.js"></script>
<!-- All JavaScript files should be linked here -->
<script src="{% static 'mysite/base/stylesbase.js' %}"></script>
<script src="{% static 'mysite/index/index.js' %}"></script>

<!-- Animation -->
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
  AOS.init({
    offset: 250,
    duration: 1400
  });
</script>

</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block index %}
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="{% static 'mysite/contact/contact.css' %}">
  <!-- Fontawesome icon -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
    integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
    crossorigin="anonymous" />
</head>


<section class="contact-section">
  <div class="contact-bg">
    <h3>Get in Touch</h3>
    <h2>contact us</h2>
    <div class="line">
      <div></div>
      <div></div>
      <div></div>
    </div>
    <p class="text">If you're looking for a PR partner who shares your vision and passion for success, we'd love to hear
      from you!
    </p>
  </div>


  <div  class="contact-body">
    <div class="contact-info">
      <div data-aos="fade-up" data-aos-offset="100">
        <span><i class="fas fa-mobile-alt"></i></span>
        <span>Phone No.</span>
        <span class="text">+91-9419584775</span>
      </div>
      <div data-aos="fade-up" data-aos-offset="100">
        <span><i class="fas fa-envelope-open"></i></span>
        <span>E-mail</span>
        <span class="text">press_pr_kmr@gmail.com</span>
      </div>
      <div data-aos="fade-up" data-aos-offset="100">
        <span><i class="fas fa-map-marker-alt"></i></span>
        <span>Address</span>
        <span class="text">Sairaa Building, Ist floor,Madina Chowk, Gawkadal, Lal Chowk
          Srinagar, Jammu and Kashmir 190001, IN</span>
      </div>
      <div data-aos="fade-up" data-aos-offset="100">
        <span><i class="fas fa-clock"></i></span>
        <span>Opening Hours</span>
        <span class="text">Monday - Saturday (9:00 AM to 5:00 PM)</span>
      </div>
    </div>

    <div data-aos="fade-up" class="contact-form">

      <form id="cntform" action="#" method="post" enctype="multipart/form-data">
        {% csrf_token %}


        <h5 class=" alert-success"></h5>
        <div>
          {{ form.firstname }}
          {{ form.lastname }}
        </div>
        <div>
          {{ form.email }}
          {{ form.phone }}
        </div>
        <div>
          {{ form.message }}
        </div>

        <input type="submit" class="send-btn" value="send message">
        <input class="reset" type="reset">
      </form>

      <div>
        <img data-aos="fade-up" src="{% static 'mysite/assets/contact-png.png' %}" alt="">
      </div>
    </div>


    <div data-aos="zoom-in" class="map">
      <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3304.8223386167642!2d74.80781191521561!3d34.07406828059998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38e18fd51441e035%3A0x343c257bcb4f0d80!2sPress%20PR!5e0!3m2!1sen!2sin!4v1640111522358!5m2!1sen!2sin"
        width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false"
        tabindex="0"></iframe>
    </div>
</section>
<!-- Add Script links Here for contact  -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"
  integrity="sha512-U6K1YLIFUWcvuw5ucmMtT9HH4t0uz3M366qrF5y4vnyH6dgDzndlcGvH/Lz5k8NFh80SN95aJ5rqGZEdaQZ7ZQ=="
  crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'mysite/contact/contact.js' %}"></script>
{% endblock %}

templates/news.html
{% extends 'base.html' %}
{% load static %}
{% block index %}

<head>
    <link rel="stylesheet" href="{% static 'mysite/news/news.css' %}">
</head>
<header>   
<section class="news">
    <div class="newsbg">
        <h1>News</h1>

    </div>
    <div class="ud">
        <h3>This page is UnderConstration</h3>
        <p>Please be Patient</p>
    </div>

</section>
{% endblock %}

templates/practivities.html
{% extends 'base.html' %}
{% load static %}
{% block index %}

<head>
    <link rel="stylesheet" href="{% static 'mysite/practivities/practivities.css' %}">
</head>
<header>   
<section class="practivities">
    <div class="practivitiesbg">
        <h1>Pr Activities</h1>

    </div>
    <div class="ud">
        <h3>This page is UnderConstration</h3>
        <p>Please be Patient</p>
    </div>

</section>
{% endblock %}

templates/services.html
{% extends 'base.html' %}
{% load static %}
{% block index %}

<head>
    <link rel="stylesheet" href="{% static 'mysite/services/services.css' %}">
</head>
<header>   
<section class="services">
    <div class="servicesbg">
        <h1>Services</h1>

    </div>
</section>

<!-- Services Section  -->
<!-- Services Section  -->
<section class="services">

    <div class="title">
        <h1>Services</h1>
        <p>We provide</p>

    </div>
    <div data-aos="slide-up" class="threelines">
        <div class="l1"></div>
        <div class="l2"></div>
        <div class="l3"></div>
    </div>
    <div class="tabs1">
        <div data-aos="fade-left" class="tab1">

            <div class="logo">
                <i class="fa fa-video"></i>
            </div>

            <h1><b> Press Conference</b></h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam sint totam reprehenderit vero,
                illo blanditiis!</p>
        </div>
        <div data-aos="fade-up" class="tab2">

            <div class="logo">
                <img src="{% static 'mysite/assets/writinglogo.png' %}" alt="">
            </div>
            <h1>Writing Services</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam sint totam reprehenderit vero,
                illo blanditiis!</p>
        </div>
        <div data-aos="fade-right" class="tab3">
            <div class="logo">
                <i class="fa fa-calendar" aria-hidden="true"></i>
            </div>
            <h1>Event Planning</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam sint totam reprehenderit vero,
                illo blanditiis!</p>
        </div>
    </div>
    <div class="tabs2">
        <div data-aos="fade-right" data-aos-offset="170" class="tab4">
            <div class="logo">
                <i class="fa fa-users"></i>
            </div>

            <h1>Celebrity PR</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam sint totam reprehenderit vero,
                illo blanditiis!</p>
        </div>
        <div data-aos="fade-down" data-aos-offset="170" class="tab5">
            <div class="logo"><i class="fas fa-chart-line"></i>
            </div>

            <h1>Trade Shows</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam sint totam reprehenderit vero,
                illo blanditiis!</p>
        </div>
        <div data-aos="fade-left" data-aos-offset="170" class="tab6">
            <div class="logo"><i class="fas fa-shopping-basket"></i>

            </div>

            <h1>Product launches</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam sint totam reprehenderit vero,
                illo blanditiis!</p>
        </div>
    </div>
    <div data-aos="slide-down" class="threelines">
        <div class="l1"></div>
        <div class="l2"></div>
        <div class="l4"></div>
    </div>
    <div data-aos="fade" class="buttonbottom">
        <h1><a href="{% url 'mysite:contact' %}"> KNOW MORE!</a></h1>
    </div>
</section>
{% endblock %}